server:
  port: 8008
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8084/
          predicates:
            - Path=/api/user-service/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
              allowedHeaders: '*'
              maxAge: 30
        - id: car-info-service
          uri: http://localhost:8082/
          predicates:
            - Path=/api/car-info-service/**
        - id: car-listing-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/car-listing-service/**
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

springdoc:
  webjars:
    prefix: /api
  cache:
    disabled: true