logging:
  level:
    root: DEBUG
server:
  port: 8008
  forward-headers-strategy: framework
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8084/
          predicates:
            - Path=/api/user-service/**
        - id: car-info-service
          uri: http://car-info-service:8082/
          predicates:
            - Path=/api/car-info-service/**
        - id: car-listing-service
          uri: http://car-listing-service:8081/
          predicates:
            - Path=/api/car-listing-service/**
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    prefer-ip-address: true

springdoc:
  webjars:
    prefix: /
  cache:
    disabled: true