spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${CARINFO_DB_NAME}
    driverClassName: com.mysql.jdbc.Driver
    username: mon2
    password: ${CARINFO_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      platform: mysql
      data-locations: classpath:data-mysql.sql
      mode: always

server:
  port: 8082
  servlet:
    context-path: /api/car-info-service

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

app-config:
  cors-config:
    allowed-origins: "http://localhost:4200,http://localhost:3000"
    max-age: 3600
    allow-credentials: true
    allowed-header: "*"
    allowed-method: "*"
    exposed-header: ""
  jwt-config:
    jwt-disabled: false
    jwt-secret: ${JWT_AUTH_SECRET}
    jwt-validity: 35

management.endpoints.web.exposure.include: refresh
