spring:
  datasource:
    url: jdbc:mysql://db:3306/carinfodbci
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: '{cipher}cc73adf2b1cfd3736c6b2f62612d67a7498ddd3625207d4db2dd4afb2e942c8b'
  jpa:
    database-platform: org.hibernate.dialect.MySQL55Dialect
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      platform: mysql
      data-locations: classpath:data-mysql.sql
      mode: always


server:
  port: 8080

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    prefer-ip-address: true

db:
  host: localhost
  port: 1111