spring:
  datasource:
    url: jdbc:mysql://db:3306/${USER_DB_NAME}
    driverClassName: com.mysql.jdbc.Driver
    username: mon2
    password: ${USER_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        '[format_sql]': true
  sql:
    init:
      platform: mysql
      data-locations: classpath:data-mysql.sql
      mode: never

server:
  port: 8084
  servlet:
    context-path: /api/user-service  

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    prefer-ip-address: true

app-config:
  cors-config:
    allowed-origins: "http://minikube:30000"
    max-age: 3600
    allow-credentials: true
    allowed-header: "*"
    allowed-method: "*"
    exposed-header: ""
  jwt-config:
    jwt-disabled: false
    jwt-secret: ${JWT_AUTH_SECRET}
    jwt-validity: 30

management.endpoints.web.exposure.include: refresh