spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdbdev
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 'P@ssw0rd'
  jpa:
    database-platform: org.hibernate.dialect.MySQL55Dialect
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        '[format_sql]': true
  sql:
    init:
      platform: mysql
      data-locations: classpath:data-mysql.sql
      mode: always

server:
  port: 8084
  servlet:
    context-path: /api/user-service  

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

jwt-config:
  jwt-disabled: true
  jwt-secret: testing
  jwt-validity: 20