spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${USER_DB_NAME}
    driverClassName: com.mysql.jdbc.Driver
    username: mon2
    password: ${USER_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        '[format_sql]': true
  sql:
    init:
      platform: mysql
      data-locations: classpath:data-mysql.sql
      mode: always

server:
  port: 8084
  servlet:
    context-path: /api/user-service  

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

app-config:
  jwt-config:
    jwt-disabled: true
    jwt-secret: ${JWT_AUTH_SECRET}
    jwt-validity: 30

management.endpoints.web.exposure.include: refresh