server:
  port: 8083
  servlet:
    context-path: /api/img-store-service

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

app-config:
  cors-config:
    enabled: false
  jwt-config:
    jwt-disabled: true
    jwt-secret: ${JWT_AUTH_SECRET}
    jwt-validity: 30

management.endpoints.web.exposure.include: refresh
